--1
SELECT * FROM DEPOSIT

--2
SELECT * FROM BORROW

--3
SELECT * FROM CUSTOMERS

--4
SELECT ACTNO,CName,Amount FROM DEPOSIT

--5
SELECT LOANNO, AMOUNT FROM BORROW

--6
SELECT LOANNO FROM BORROW WHERE BNAME='ANDHERI'

--7
SELECT ACTNO,Amount FROM DEPOSIT WHERE ACTNO=106

--8
SELECT CNAME FROM BORROW WHERE AMOUNT>5000

--9
SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-01'

--10
SELECT CNAME FROM DEPOSIT WHERE ACTNO<105

--11
SELECT CNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'

--12
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105

--13
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000

--14
SELECT CNAME FROM DEPOSIT WHERE BNAME<>'ANDHERI'

--15
SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

--16
SELECT ACTNO,CNAME,AMOUNT FROM	DEPOSIT 
WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G.ROAD' AND ACTNO<104

--17
SELECT TOP 5 * FROM CUSTOMERS

--18
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT>1000

--19
SELECT TOP 3  LOANNO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'

--20
SELECT DISTINCT CITY FROM CUSTOMERS

--21
SELECT DISTINCT BNAME FROM BRANCH

--22
SELECT * FROM CUSTOMERS ORDER BY CITY

--23
SELECT * FROM DEPOSIT ORDER BY AMOUNT DESC

--24
SELECT * FROM CUSTOMERS ORDER BY CITY DESC

--25
SELECT DISTINCT BNAME AS UNI_Borrowers FROM BORROW
